apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-checker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ipChecker.replicaCount }}
  selector:
    matchLabels:
      app: ip-checker
  template:
    metadata:
      labels:
        app: ip-checker
    spec:
      containers:
        - name: ip-checker
          image: "{{ .Values.ipChecker.image }}:{{ .Values.ipChecker.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            {{- range $key, $value := .Values.ipChecker.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}