apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ip-checker
  namespace: {{ .Values.namespace }}
  labels:
    app: ip-checker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ipChecker.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ip-checker
                port:
                  number: {{ .Values.ipChecker.service.port }}