services:
  ip-checker:
    build: .
    image: ip-checker-image:latest
    container_name: ip-checker-container 
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"