apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-admin
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
