apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    app: {{ .Release.Name }}-grafana
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
