apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.config.evaluationInterval }}
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
{{- if .Values.global.ipCheckerMetricsEnabled }}
      - job_name: ip-checker
        metrics_path: /metrics
        static_configs:
          - targets:
{{- range .Values.global.ipCheckerMetricsTargets }}
              - {{ . | quote }}
{{- end }}
{{- end }}
